allowBuilds:
  esbuild: set this to true or false
  msw: set this to true or false
  sharp: set this to true or false
minimumReleaseAgeExclude:
  - '@ai-sdk/gateway@4.0.54'
  - '@ai-sdk/harness-opencode@1.0.76'
  - '@ai-sdk/harness@1.0.75'
  - '@ai-sdk/sandbox-vercel@1.0.75'
  - ai@7.0.68
